import type { NewRegion } from '../schema';

export const regionsSeedData: NewRegion[] = [
  {
    sido_code: '11',
    sigungu_code: null,
    sido_name: '서울특별시',
    sigungu_name: null,
    level: 'sido',
    slug: 'seoul',
    population_65plus: 1_572_000,
    single_elderly_households: 378_000,
  },
  {
    sido_code: '26',
    sigungu_code: null,
    sido_name: '부산광역시',
    sigungu_name: null,
    level: 'sido',
    slug: 'busan',
    population_65plus: 698_000,
    single_elderly_households: 163_000,
  },
  {
    sido_code: '27',
    sigungu_code: null,
    sido_name: '대구광역시',
    sigungu_name: null,
    level: 'sido',
    slug: 'daegu',
    population_65plus: 408_000,
    single_elderly_households: 93_000,
  },
  {
    sido_code: '28',
    sigungu_code: null,
    sido_name: '인천광역시',
    sigungu_name: null,
    level: 'sido',
    slug: 'incheon',
    population_65plus: 373_000,
    single_elderly_households: 84_000,
  },
  {
    sido_code: '29',
    sigungu_code: null,
    sido_name: '광주광역시',
    sigungu_name: null,
    level: 'sido',
    slug: 'gwangju',
    population_65plus: 222_000,
    single_elderly_households: 54_000,
  },
  {
    sido_code: '30',
    sigungu_code: null,
    sido_name: '대전광역시',
    sigungu_name: null,
    level: 'sido',
    slug: 'daejeon',
    population_65plus: 214_000,
    single_elderly_households: 50_000,
  },
  {
    sido_code: '31',
    sigungu_code: null,
    sido_name: '울산광역시',
    sigungu_name: null,
    level: 'sido',
    slug: 'ulsan',
    population_65plus: 142_000,
    single_elderly_households: 30_000,
  },
  {
    sido_code: '36',
    sigungu_code: null,
    sido_name: '세종특별자치시',
    sigungu_name: null,
    level: 'sido',
    slug: 'sejong',
    population_65plus: 43_000,
    single_elderly_households: 9_000,
  },
  {
    sido_code: '41',
    sigungu_code: null,
    sido_name: '경기도',
    sigungu_name: null,
    level: 'sido',
    slug: 'gyeonggi',
    population_65plus: 1_790_000,
    single_elderly_households: 390_000,
  },
  {
    sido_code: '42',
    sigungu_code: null,
    sido_name: '강원특별자치도',
    sigungu_name: null,
    level: 'sido',
    slug: 'gangwon',
    population_65plus: 357_000,
    single_elderly_households: 90_000,
  },
  {
    sido_code: '43',
    sigungu_code: null,
    sido_name: '충청북도',
    sigungu_name: null,
    level: 'sido',
    slug: 'chungbuk',
    population_65plus: 310_000,
    single_elderly_households: 76_000,
  },
  {
    sido_code: '44',
    sigungu_code: null,
    sido_name: '충청남도',
    sigungu_name: null,
    level: 'sido',
    slug: 'chungnam',
    population_65plus: 420_000,
    single_elderly_households: 108_000,
  },
  {
    sido_code: '45',
    sigungu_code: null,
    sido_name: '전북특별자치도',
    sigungu_name: null,
    level: 'sido',
    slug: 'jeonbuk',
    population_65plus: 430_000,
    single_elderly_households: 112_000,
  },
  {
    sido_code: '46',
    sigungu_code: null,
    sido_name: '전라남도',
    sigungu_name: null,
    level: 'sido',
    slug: 'jeonnam',
    population_65plus: 490_000,
    single_elderly_households: 130_000,
  },
  {
    sido_code: '47',
    sigungu_code: null,
    sido_name: '경상북도',
    sigungu_name: null,
    level: 'sido',
    slug: 'gyeongbuk',
    population_65plus: 580_000,
    single_elderly_households: 150_000,
  },
  {
    sido_code: '48',
    sigungu_code: null,
    sido_name: '경상남도',
    sigungu_name: null,
    level: 'sido',
    slug: 'gyeongnam',
    population_65plus: 560_000,
    single_elderly_households: 133_000,
  },
  {
    sido_code: '50',
    sigungu_code: null,
    sido_name: '제주특별자치도',
    sigungu_name: null,
    level: 'sido',
    slug: 'jeju',
    population_65plus: 125_000,
    single_elderly_households: 29_000,
  },
];
