import type { NewRobot } from '../schema';

export const robotsSeedData: NewRobot[] = [
  // ─── 한국 로봇 8개 ───────────────────────────────────────────
  {
    slug: 'hyodol',
    name_ko: '효돌',
    name_en: 'Hyodol',
    manufacturer: '㈜효돌',
    manufacturer_country: 'KR',
    category: 'companion',
    korea_market: true,
    price_min: 1_980_000,
    price_max: 1_980_000,
    subscription_monthly: 49_800,
    rental_available: true,
    release_year: 2019,
    manufacturer_url: 'https://www.hyodol.com',
    description_short:
      '국내 최초 AI 돌봄 로봇. 노인의 말벗·건강 체크·낙상 감지 기능을 갖춘 인형형 케어 로봇.',
    features_json: JSON.stringify([
      'AI 대화(말벗)',
      '복약 알림',
      '낙상 감지',
      '보호자 앱 연동',
      '응급 호출',
      '건강 체크',
    ]),
    hero_image_url: null,
  },
  {
    slug: 'dasom-k',
    name_ko: '다솜K',
    name_en: 'Dasom-K',
    manufacturer: '한국로봇융합연구원',
    manufacturer_country: 'KR',
    category: 'senior_care',
    korea_market: true,
    price_min: null,
    price_max: null,
    subscription_monthly: null,
    rental_available: true,
    release_year: 2020,
    manufacturer_url: 'https://www.kiro.re.kr',
    description_short:
      '한국로봇융합연구원이 개발한 가정형 노인 돌봄 로봇. 이동식 플랫폼과 센서로 생활 패턴을 모니터링.',
    features_json: JSON.stringify([
      '생활 패턴 모니터링',
      '이동형 플랫폼',
      '응급 알림',
      '보호자 연동',
    ]),
    hero_image_url: null,
  },
  {
    slug: 'dasom-b',
    name_ko: '다솜B',
    name_en: 'Dasom-B',
    manufacturer: '한국로봇융합연구원',
    manufacturer_country: 'KR',
    category: 'senior_care',
    korea_market: true,
    price_min: null,
    price_max: null,
    subscription_monthly: null,
    rental_available: true,
    release_year: 2021,
    manufacturer_url: 'https://www.kiro.re.kr',
    description_short:
      '한국로봇융합연구원의 배회 감지 특화형 돌봄 로봇. 치매 어르신의 안전한 생활 환경을 지원.',
    features_json: JSON.stringify([
      '배회 감지',
      '치매 어르신 케어',
      '위치 추적',
      '보호자 알림',
    ]),
    hero_image_url: null,
  },
  {
    slug: 'dasom-m',
    name_ko: '다솜M',
    name_en: 'Dasom-M',
    manufacturer: '한국로봇융합연구원',
    manufacturer_country: 'KR',
    category: 'monitoring',
    korea_market: true,
    price_min: null,
    price_max: null,
    subscription_monthly: null,
    rental_available: true,
    release_year: 2022,
    manufacturer_url: 'https://www.kiro.re.kr',
    description_short:
      '한국로봇융합연구원의 시설형 모니터링 로봇. 요양원·복지관 환경에서 다수 어르신을 동시에 모니터링.',
    features_json: JSON.stringify([
      '다중 모니터링',
      '시설 환경 최적화',
      '낙상 감지',
      '중앙 관제 연동',
    ]),
    hero_image_url: null,
  },
  {
    slug: 'kkumdoli',
    name_ko: '꿈돌이',
    name_en: 'Kkumdoli',
    manufacturer: '(주)유진로봇',
    manufacturer_country: 'KR',
    category: 'companion',
    korea_market: true,
    price_min: 500_000,
    price_max: 800_000,
    subscription_monthly: 30_000,
    rental_available: true,
    release_year: 2021,
    manufacturer_url: 'https://www.yujinrobot.com',
    description_short:
      '유진로봇이 개발한 아동·노인 대상 감성 케어 로봇. 대화와 놀이로 정서적 교감을 제공.',
    features_json: JSON.stringify([
      '감성 대화',
      '노래·동화',
      '표정 인식',
      '원격 화상 통화',
    ]),
    hero_image_url: null,
  },
  {
    slug: 'bomi',
    name_ko: '보미',
    name_en: 'Bomi',
    manufacturer: '(주)클로봇',
    manufacturer_country: 'KR',
    category: 'companion',
    korea_market: true,
    price_min: 1_200_000,
    price_max: 1_500_000,
    subscription_monthly: 39_000,
    rental_available: true,
    release_year: 2022,
    manufacturer_url: 'https://www.clobot.co.kr',
    description_short:
      '클로봇의 AI 기반 어르신 돌봄 로봇. 자연어 대화와 건강 관리 기능으로 독거노인의 고립 예방.',
    features_json: JSON.stringify([
      'AI 자연어 대화',
      '복약 관리',
      '건강 설문',
      '긴급 SOS',
      '가족 연락',
    ]),
    hero_image_url: null,
  },
  {
    slug: 'raemi',
    name_ko: '래미',
    name_en: 'Raemi',
    manufacturer: '(주)라온테크',
    manufacturer_country: 'KR',
    category: 'rehabilitation',
    korea_market: true,
    price_min: 3_000_000,
    price_max: 5_000_000,
    subscription_monthly: null,
    rental_available: true,
    release_year: 2021,
    manufacturer_url: 'https://www.raontech.com',
    description_short:
      '노인·장애인의 상지 재활을 돕는 웨어러블 로봇. 반복 운동을 통한 근기능 회복 지원.',
    features_json: JSON.stringify([
      '상지 재활 운동',
      '웨어러블 설계',
      '운동 데이터 기록',
      '의료진 원격 모니터링',
    ]),
    hero_image_url: null,
  },
  {
    slug: 'maibom',
    name_ko: '마이봄',
    name_en: 'Maibom',
    manufacturer: '(주)마이리얼트립 로보틱스',
    manufacturer_country: 'KR',
    category: 'companion',
    korea_market: true,
    price_min: 990_000,
    price_max: 1_200_000,
    subscription_monthly: 29_000,
    rental_available: false,
    release_year: 2023,
    manufacturer_url: null,
    description_short:
      '국내 스타트업이 개발한 소형 AI 반려 로봇. 감성 인식 기술로 어르신의 기분을 파악하고 맞춤 대화 제공.',
    features_json: JSON.stringify([
      '감성 인식',
      '맞춤 대화',
      'LED 표정 표현',
      '수면 패턴 분석',
    ]),
    hero_image_url: null,
  },

  // ─── 글로벌 로봇 5개 ─────────────────────────────────────────
  {
    slug: 'aibo',
    name_ko: 'aibo (아이보)',
    name_en: 'aibo',
    manufacturer: 'Sony Corporation',
    manufacturer_country: 'JP',
    category: 'companion',
    korea_market: false,
    price_min: 1_500_000,
    price_max: 1_800_000,
    subscription_monthly: 30_000,
    rental_available: false,
    release_year: 2018,
    manufacturer_url: 'https://aibo.sony.jp',
    description_short:
      '소니의 AI 반려 강아지 로봇. 딥러닝 기반 감정 학습으로 주인과의 유대감을 형성하는 엔터테인먼트 로봇.',
    features_json: JSON.stringify([
      '딥러닝 감정 학습',
      '주인 얼굴 인식',
      '자율 행동',
      '앱 연동',
      '클라우드 AI 업데이트',
    ]),
    hero_image_url: null,
  },
  {
    slug: 'lovot',
    name_ko: 'LOVOT (러봇)',
    name_en: 'LOVOT',
    manufacturer: 'GROOVE X Inc.',
    manufacturer_country: 'JP',
    category: 'companion',
    korea_market: false,
    price_min: 5_000_000,
    price_max: 6_000_000,
    subscription_monthly: 100_000,
    rental_available: false,
    release_year: 2019,
    manufacturer_url: 'https://lovot.life',
    description_short:
      'GROOVE X의 감성형 반려 로봇. 따뜻한 체온과 풍부한 감정 표현으로 사람의 정서적 안정을 돕는 로봇.',
    features_json: JSON.stringify([
      '체온 발열 기능',
      '감정 표현',
      '얼굴 인식',
      '안아주기 반응',
      '다인식 반응',
    ]),
    hero_image_url: null,
  },
  {
    slug: 'moflin',
    name_ko: 'Moflin (모플린)',
    name_en: 'Moflin',
    manufacturer: 'Vanguard Industries Inc.',
    manufacturer_country: 'JP',
    category: 'companion',
    korea_market: false,
    price_min: 800_000,
    price_max: 1_000_000,
    subscription_monthly: null,
    rental_available: false,
    release_year: 2022,
    manufacturer_url: 'https://moflin.com',
    description_short:
      'AI 기반 털뭉치형 감성 로봇. 소리와 촉각 센서로 감정을 학습하며 성장하는 개성 있는 반려 로봇.',
    features_json: JSON.stringify([
      'AI 감정 학습',
      '촉각 반응',
      '음성 반응',
      '개성 성장',
    ]),
    hero_image_url: null,
  },
  {
    slug: 'elliq',
    name_ko: 'ElliQ (엘리큐)',
    name_en: 'ElliQ',
    manufacturer: 'Intuition Robotics',
    manufacturer_country: 'IL',
    category: 'senior_care',
    korea_market: false,
    price_min: null,
    price_max: null,
    subscription_monthly: 50_000,
    rental_available: true,
    release_year: 2022,
    manufacturer_url: 'https://elliq.com',
    description_short:
      '이스라엘 Intuition Robotics의 노인 전용 AI 동반자 로봇. 대화·건강 관리·사회 연결을 통해 고립을 예방.',
    features_json: JSON.stringify([
      'AI 대화',
      '건강 리마인더',
      '화상 통화',
      '인지 훈련 게임',
      '감정 분석',
    ]),
    hero_image_url: null,
  },
  {
    slug: 'paro',
    name_ko: 'PARO (파로)',
    name_en: 'PARO',
    manufacturer: '국립산업기술종합연구소(AIST)',
    manufacturer_country: 'JP',
    category: 'rehabilitation',
    korea_market: false,
    price_min: 6_000_000,
    price_max: 8_000_000,
    subscription_monthly: null,
    rental_available: true,
    release_year: 2004,
    manufacturer_url: 'https://www.parorobots.com',
    description_short:
      '일본 국립산업기술종합연구소가 개발한 치료용 물개 로봇. 치매·우울증 환자의 정서 안정 효과가 임상으로 검증된 의료기기 인증 로봇.',
    features_json: JSON.stringify([
      '치료 목적 설계',
      '촉각 반응',
      '소리 반응',
      '빛 감지',
      '의료기기 인증(일본·미국)',
      '치매 환자 정서 안정',
    ]),
    hero_image_url: null,
  },
];
