import type { NewSupportProgram } from '../schema';

// region_id 매핑 (regions 시드 삽입 순서 기준)
// 1=서울, 2=부산, 3=대구, 4=인천, 5=광주, 6=대전, 7=울산, 8=세종
// 9=경기, 10=강원, 11=충북, 12=충남, 13=전북, 14=전남, 15=경북, 16=경남, 17=제주

export const supportProgramsSeedData: Omit<NewSupportProgram, 'id'>[] = [
  // ─── 서울 ────────────────────────────────────────────────────
  {
    slug: 'seoul-2024-care-robot-distribution',
    region_id: 1,
    name_ko: '서울시 2024년 반려로봇 보급사업',
    program_type: 'free_distribution',
    eligibility_json: JSON.stringify({
      age: '만 65세 이상',
      residence: '서울시 거주',
      household: '홀로 거주 어르신 우선',
      income: '기초생활수급자, 차상위계층 우선',
    }),
    application_method: '거주지 자치구 노인복지팀 방문 또는 전화 신청 후 대상자 선정',
    application_url: 'https://www.seoul.go.kr/',
    distribution_count: 480,
    source_url: 'https://www.seoul.go.kr/news/news_report.do',
    source_license: '공공누리 제1유형',
    status: 'active',
    human_reviewed: true,
  },
  {
    slug: 'seoul-2024-senior-robot-rental',
    region_id: 1,
    name_ko: '서울시 어르신 AI 돌봄로봇 대여사업',
    program_type: 'rental',
    eligibility_json: JSON.stringify({
      age: '만 70세 이상',
      residence: '서울시 25개 자치구 거주',
      household: '독거노인 또는 노인 부부 가구',
      income: '소득 무관, 취약계층 우선',
    }),
    application_method: '동주민센터 노인복지담당 방문 신청, 복지관 연계 신청 가능',
    application_url: 'https://www.seoul.go.kr/',
    distribution_count: 320,
    source_url: 'https://welfare.seoul.go.kr/',
    source_license: '공공누리 제1유형',
    status: 'active',
    human_reviewed: true,
  },

  // ─── 부산 ────────────────────────────────────────────────────
  {
    slug: 'busan-2024-iot-care-robot',
    region_id: 2,
    name_ko: '부산시 2024 ICT 융합 돌봄로봇 보급사업',
    program_type: 'free_distribution',
    eligibility_json: JSON.stringify({
      age: '만 65세 이상',
      residence: '부산광역시 거주',
      household: '독거노인 우선 선발',
      income: '기초생활수급자, 차상위계층',
    }),
    application_method: '부산시 사회서비스원 또는 거주지 구청 노인복지과 방문·전화 신청',
    application_url: 'https://www.busan.go.kr/',
    distribution_count: 250,
    source_url: 'https://www.busan.go.kr/welfare/seniorRobot',
    source_license: '공공누리 제1유형',
    status: 'active',
    human_reviewed: true,
  },

  // ─── 대구 ────────────────────────────────────────────────────
  {
    slug: 'daegu-2024-ai-companion-robot',
    region_id: 3,
    name_ko: '대구시 AI 반려로봇 어르신 보급사업',
    program_type: 'free_distribution',
    eligibility_json: JSON.stringify({
      age: '만 65세 이상',
      residence: '대구광역시 거주',
      household: '독거노인 또는 노인 부부',
      income: '기초생활수급자 우선',
    }),
    application_method: '거주지 동주민센터 또는 대구시 노인복지과 방문 신청',
    application_url: 'https://www.daegu.go.kr/',
    distribution_count: 180,
    source_url: 'https://www.daegu.go.kr/social/index.do',
    source_license: '공공누리 제1유형',
    status: 'active',
    human_reviewed: true,
  },

  // ─── 인천 ────────────────────────────────────────────────────
  {
    slug: 'incheon-2024-care-robot-pilot',
    region_id: 4,
    name_ko: '인천시 2024 어르신 돌봄로봇 시범보급사업',
    program_type: 'free_distribution',
    eligibility_json: JSON.stringify({
      age: '만 65세 이상',
      residence: '인천광역시 거주',
      household: '홀로 생활하는 어르신',
      income: '기초생활수급자, 차상위계층 우선 선발',
    }),
    application_method: '인천복지재단 또는 거주지 구·군 노인복지팀 방문 신청',
    application_url: 'https://www.incheon.go.kr/',
    distribution_count: 160,
    source_url: 'https://www.incheon.go.kr/health/index',
    source_license: '공공누리 제1유형',
    status: 'active',
    human_reviewed: true,
  },

  // ─── 광주 ────────────────────────────────────────────────────
  {
    slug: 'gwangju-2024-senior-robot-distribution',
    region_id: 5,
    name_ko: '광주시 노인 AI 돌봄로봇 무상 보급',
    program_type: 'free_distribution',
    eligibility_json: JSON.stringify({
      age: '만 65세 이상',
      residence: '광주광역시 거주',
      household: '독거노인 우선',
      income: '기초생활수급자, 차상위 우선',
    }),
    application_method: '광주시 5개 구청 노인복지과 방문 신청 또는 주민센터 위탁 신청',
    application_url: 'https://www.gwangju.go.kr/',
    distribution_count: 120,
    source_url: 'https://www.gwangju.go.kr/contents.do?key=4143',
    source_license: '공공누리 제1유형',
    status: 'active',
    human_reviewed: true,
  },

  // ─── 대전 ────────────────────────────────────────────────────
  {
    slug: 'daejeon-2024-care-robot-subsidy',
    region_id: 6,
    name_ko: '대전시 돌봄로봇 구입비 지원사업',
    program_type: 'subsidy',
    eligibility_json: JSON.stringify({
      age: '만 65세 이상',
      residence: '대전광역시 거주',
      household: '독거 또는 노인 부부 가구',
      income: '중위소득 100% 이하',
    }),
    application_method: '대전시 구청 복지정책과 방문 신청, 구입 영수증 제출 후 지원금 지급',
    application_url: 'https://www.daejeon.go.kr/',
    distribution_count: 100,
    source_url: 'https://www.daejeon.go.kr/wel/index.do',
    source_license: '공공누리 제1유형',
    status: 'active',
    human_reviewed: true,
  },

  // ─── 울산 ────────────────────────────────────────────────────
  {
    slug: 'ulsan-2024-robot-care-program',
    region_id: 7,
    name_ko: '울산시 어르신 생활지원 로봇 보급사업',
    program_type: 'free_distribution',
    eligibility_json: JSON.stringify({
      age: '만 65세 이상',
      residence: '울산광역시 거주',
      household: '독거노인 또는 조손 가정',
      income: '기초생활수급자 우선',
    }),
    application_method: '울산시 5개 구·군 노인복지과 방문 신청',
    application_url: 'https://www.ulsan.go.kr/',
    distribution_count: 90,
    source_url: 'https://www.ulsan.go.kr/welfare',
    source_license: '공공누리 제1유형',
    status: 'active',
    human_reviewed: true,
  },

  // ─── 세종 ────────────────────────────────────────────────────
  {
    slug: 'sejong-2024-smart-care-robot',
    region_id: 8,
    name_ko: '세종시 스마트돌봄 로봇 지원사업',
    program_type: 'free_distribution',
    eligibility_json: JSON.stringify({
      age: '만 65세 이상',
      residence: '세종특별자치시 거주',
      household: '독거 어르신 우선',
      income: '기초생활수급자, 차상위계층',
    }),
    application_method: '세종시 읍·면·동 행정복지센터 방문 신청',
    application_url: 'https://www.sejong.go.kr/',
    distribution_count: 50,
    source_url: 'https://www.sejong.go.kr/welfare/index.do',
    source_license: '공공누리 제1유형',
    status: 'active',
    human_reviewed: true,
  },

  // ─── 경기 ────────────────────────────────────────────────────
  {
    slug: 'gyeonggi-2024-care-robot-large',
    region_id: 9,
    name_ko: '경기도 2024 어르신 돌봄로봇 대규모 보급사업',
    program_type: 'free_distribution',
    eligibility_json: JSON.stringify({
      age: '만 65세 이상',
      residence: '경기도 31개 시·군 거주',
      household: '독거노인 우선, 노인 부부 가구 포함',
      income: '기초생활수급자, 차상위계층 우선',
    }),
    application_method: '경기복지재단 또는 거주지 시·군 노인복지과 방문 신청',
    application_url: 'https://www.gg.go.kr/',
    distribution_count: 800,
    source_url: 'https://www.gg.go.kr/welfare',
    source_license: '공공누리 제1유형',
    status: 'active',
    human_reviewed: true,
  },
  {
    slug: 'gyeonggi-2024-rental-robot-program',
    region_id: 9,
    name_ko: '경기도 AI 돌봄로봇 저비용 대여 지원',
    program_type: 'rental',
    eligibility_json: JSON.stringify({
      age: '만 60세 이상',
      residence: '경기도 거주',
      household: '소득 무관',
      income: '중위소득 120% 이하 시 비용 지원',
    }),
    application_method: '경기도 디지털복지센터 온라인 신청 또는 시·군 방문 신청',
    application_url: 'https://www.gg.go.kr/',
    distribution_count: 400,
    source_url: 'https://www.gg.go.kr/digitalwelfare',
    source_license: '공공누리 제1유형',
    status: 'active',
    human_reviewed: true,
  },

  // ─── 강원 ────────────────────────────────────────────────────
  {
    slug: 'gangwon-2024-rural-care-robot',
    region_id: 10,
    name_ko: '강원특별자치도 농어촌 어르신 돌봄로봇 보급',
    program_type: 'free_distribution',
    eligibility_json: JSON.stringify({
      age: '만 65세 이상',
      residence: '강원특별자치도 읍·면 지역 거주 우선',
      household: '독거노인, 거동 불편 어르신',
      income: '기초생활수급자 우선',
    }),
    application_method: '읍·면·동 행정복지센터 방문 신청, 사회복지사 가정방문 신청 연계',
    application_url: 'https://www.gwd.go.kr/',
    distribution_count: 200,
    source_url: 'https://www.gwd.go.kr/welfare',
    source_license: '공공누리 제1유형',
    status: 'active',
    human_reviewed: true,
  },

  // ─── 충북 ────────────────────────────────────────────────────
  {
    slug: 'chungbuk-2024-care-robot-program',
    region_id: 11,
    name_ko: '충청북도 어르신 AI 안심돌봄 로봇 지원',
    program_type: 'free_distribution',
    eligibility_json: JSON.stringify({
      age: '만 65세 이상',
      residence: '충청북도 거주',
      household: '독거노인 또는 노인 단독 가구',
      income: '기초생활수급자, 차상위계층 우선',
    }),
    application_method: '충북도 시·군 노인복지과 방문 신청',
    application_url: 'https://www.cb21.go.kr/',
    distribution_count: 170,
    source_url: 'https://www.chungbuk.go.kr/welfare',
    source_license: '공공누리 제1유형',
    status: 'active',
    human_reviewed: true,
  },

  // ─── 충남 ────────────────────────────────────────────────────
  {
    slug: 'chungnam-2024-senior-care-robot',
    region_id: 12,
    name_ko: '충청남도 고령사회 대응 돌봄로봇 무상 지원',
    program_type: 'free_distribution',
    eligibility_json: JSON.stringify({
      age: '만 65세 이상',
      residence: '충청남도 거주',
      household: '독거노인 우선, 노인 부부 가구 포함',
      income: '기초생활수급자, 차상위 우선',
    }),
    application_method: '충남 15개 시·군 노인복지담당 방문 신청',
    application_url: 'https://www.chungnam.go.kr/',
    distribution_count: 220,
    source_url: 'https://www.chungnam.go.kr/welfare/index.do',
    source_license: '공공누리 제1유형',
    status: 'active',
    human_reviewed: true,
  },

  // ─── 전북 ────────────────────────────────────────────────────
  {
    slug: 'jeonbuk-2024-robot-care-support',
    region_id: 13,
    name_ko: '전북특별자치도 어르신 돌봄로봇 보급 확대',
    program_type: 'free_distribution',
    eligibility_json: JSON.stringify({
      age: '만 65세 이상',
      residence: '전북특별자치도 거주',
      household: '독거노인 또는 조손 가구',
      income: '기초생활수급자, 차상위계층',
    }),
    application_method: '전북복지재단 또는 시·군 노인복지과 신청, 사회복지사 추천 신청 가능',
    application_url: 'https://www.jeonbuk.go.kr/',
    distribution_count: 230,
    source_url: 'https://www.jeonbuk.go.kr/welfare',
    source_license: '공공누리 제1유형',
    status: 'active',
    human_reviewed: true,
  },

  // ─── 전남 ────────────────────────────────────────────────────
  {
    slug: 'jeonnam-2024-care-robot-aging',
    region_id: 14,
    name_ko: '전라남도 초고령사회 어르신 AI 돌봄로봇 보급',
    program_type: 'free_distribution',
    eligibility_json: JSON.stringify({
      age: '만 65세 이상',
      residence: '전라남도 22개 시·군 거주',
      household: '독거노인 또는 거동 불편 어르신',
      income: '기초생활수급자 우선, 차상위계층 포함',
    }),
    application_method: '전남 22개 시·군 사회복지과 방문 신청, 노인돌봄서비스 연계 신청 가능',
    application_url: 'https://www.jeonnam.go.kr/',
    distribution_count: 280,
    source_url: 'https://www.jeonnam.go.kr/welfare/index.jsp',
    source_license: '공공누리 제1유형',
    status: 'active',
    human_reviewed: true,
  },
  {
    slug: 'jeonnam-2024-robot-rd-grant',
    region_id: 14,
    name_ko: '전남 돌봄로봇 실증·개발 지원사업',
    program_type: 'rd_grant',
    eligibility_json: JSON.stringify({
      target: '돌봄로봇 개발·실증 기업',
      region: '전라남도 소재 또는 전남 어르신 대상 실증',
      condition: '중소기업, 스타트업 우대',
    }),
    application_method: '전남테크노파크 또는 전남 경제통상진흥원 공고 확인 후 서류 제출',
    application_url: 'https://www.jntp.or.kr/',
    distribution_count: null,
    source_url: 'https://www.jntp.or.kr/biz',
    source_license: '공공누리 제1유형',
    status: 'active',
    human_reviewed: true,
  },

  // ─── 경북 ────────────────────────────────────────────────────
  {
    slug: 'gyeongbuk-2024-care-robot-support',
    region_id: 15,
    name_ko: '경상북도 노인 맞춤돌봄 AI 로봇 지원사업',
    program_type: 'free_distribution',
    eligibility_json: JSON.stringify({
      age: '만 65세 이상',
      residence: '경상북도 거주',
      household: '독거노인, 조손 가구, 거동 불편 어르신',
      income: '기초생활수급자, 차상위계층 우선',
    }),
    application_method: '경북 23개 시·군 노인복지과 방문 신청 또는 재가복지센터 추천',
    application_url: 'https://www.gb.go.kr/',
    distribution_count: 310,
    source_url: 'https://www.gb.go.kr/welfare',
    source_license: '공공누리 제1유형',
    status: 'active',
    human_reviewed: true,
  },

  // ─── 경남 ────────────────────────────────────────────────────
  {
    slug: 'gyeongnam-2024-robot-welfare',
    region_id: 16,
    name_ko: '경상남도 어르신 복지로봇 보급사업',
    program_type: 'free_distribution',
    eligibility_json: JSON.stringify({
      age: '만 65세 이상',
      residence: '경상남도 거주',
      household: '독거노인 또는 노인 부부 가구',
      income: '기초생활수급자, 차상위계층 우선',
    }),
    application_method: '경남 18개 시·군 노인복지담당 방문 신청 또는 노인돌봄기본서비스 연계',
    application_url: 'https://www.gyeongnam.go.kr/',
    distribution_count: 290,
    source_url: 'https://www.gyeongnam.go.kr/welfare',
    source_license: '공공누리 제1유형',
    status: 'active',
    human_reviewed: true,
  },

  // ─── 제주 ────────────────────────────────────────────────────
  {
    slug: 'jeju-2024-care-robot-island',
    region_id: 17,
    name_ko: '제주특별자치도 어르신 AI 돌봄로봇 무상 보급',
    program_type: 'free_distribution',
    eligibility_json: JSON.stringify({
      age: '만 65세 이상',
      residence: '제주특별자치도 거주 (제주시·서귀포시 포함)',
      household: '독거노인 또는 노인 단독 가구',
      income: '기초생활수급자, 차상위계층 우선',
    }),
    application_method: '제주시·서귀포시 읍·면·동 주민센터 방문 신청',
    application_url: 'https://www.jeju.go.kr/',
    distribution_count: 80,
    source_url: 'https://www.jeju.go.kr/welfare/index.htm',
    source_license: '공공누리 제1유형',
    status: 'active',
    human_reviewed: true,
  },

  // ─── 국가 단위 사업 (region_id = null) ──────────────────────────
  {
    slug: 'mohw-2024-national-care-robot',
    region_id: null,
    name_ko: '보건복지부 2024년 취약노인 AI 돌봄로봇 전국 보급사업',
    program_type: 'free_distribution',
    eligibility_json: JSON.stringify([
      { category: '연령', requirement: '만 65세 이상 노인' },
      { category: '가구 형태', requirement: '독거 또는 노인 부부 가구' },
      { category: '소득', requirement: '기초생활수급자, 차상위계층 (소득 하위 70% 이하)' },
      { category: '신청 지역', requirement: '전국 17개 시도 (지역별 선착순)' },
    ]),
    application_method: '거주지 읍·면·동 주민센터 방문 신청;노인맞춤돌봄서비스 담당자 추천;복지로(bokjiro.go.kr) 온라인 신청',
    application_url: 'https://www.bokjiro.go.kr',
    budget: 15_000_000_000,
    distribution_count: 5000,
    source_url: 'https://www.mohw.go.kr/board.es?mid=a10503000000&bid=0027',
    source_license: '공공누리 제1유형',
    source_publication_date: new Date('2024-01-15'),
    status: 'active',
    human_reviewed: true,
  },
  {
    slug: 'mohw-2024-welfare-facility-robot',
    region_id: null,
    name_ko: '보건복지부 2024년 노인복지시설 돌봄로봇 도입 지원사업',
    program_type: 'subsidy',
    eligibility_json: JSON.stringify([
      { category: '대상 시설', requirement: '노인요양시설, 주·야간보호시설, 노인복지관' },
      { category: '입소 정원', requirement: '입소 정원 10인 이상 시설 우선' },
      { category: '사업 유형', requirement: '사회복지법인 또는 비영리법인 운영 시설' },
      { category: '지원 한도', requirement: '시설당 최대 5대, 구매가의 50% 보조' },
    ]),
    application_method: '시설 소재 시·군·구청 노인복지과 신청;한국사회복지협의회 포털(welfare.net) 신청;사업계획서 및 법인 서류 제출 필수',
    application_url: 'https://www.welfare.net',
    budget: 8_000_000_000,
    distribution_count: 1200,
    source_url: 'https://www.mohw.go.kr/board.es?mid=a10503000000&bid=0027',
    source_license: '공공누리 제1유형',
    source_publication_date: new Date('2024-02-01'),
    status: 'active',
    human_reviewed: true,
  },
  {
    slug: 'korearobot-2024-rd-care-robot',
    region_id: null,
    name_ko: '한국로봇산업진흥원 2024년 돌봄로봇 R&D 실증 지원사업',
    program_type: 'rd_grant',
    eligibility_json: JSON.stringify([
      { category: '대상', requirement: '돌봄로봇 개발 중소기업, 스타트업, 연구기관' },
      { category: '지원 유형', requirement: '시제품 제작, 현장 실증, 인증 취득 비용' },
      { category: '사업화', requirement: '실증 완료 후 2년 내 제품 출시 계획 필수' },
    ]),
    application_method: '한국로봇산업진흥원(korearobot.or.kr) 사업 공고 확인 후 온라인 신청;사업계획서, 기술개발 계획서 제출',
    application_url: 'https://www.korearobot.or.kr',
    budget: 5_000_000_000,
    distribution_count: null,
    source_url: 'https://www.korearobot.or.kr/biz',
    source_license: '공공누리 제1유형',
    source_publication_date: new Date('2024-03-01'),
    status: 'active',
    human_reviewed: true,
  },
];
